build: false
version: "{branch}-{build}"

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  PYTHON_PATH: C:\Python27

for:
  - matrix:
      only:
        - image: Visual Studio 2015
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  - matrix:
      only:
        - image: Visual Studio 2017
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_67_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib32-msvc-14.1
      EXTRAOPTS: --std=c++17

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cinst ninja
  - call "%VS%" x86
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install bfg9000

  # Install the latest master revision of mettle.
  - git clone https://github.com/jimporter/mettle.git
  - cd mettle
  - copy ..\include\bencode.hpp include\bencode.hpp
  - 9k build --backend=ninja --prefix=C:\mettle %EXTRAOPTS%
  - cd build
  - ninja install
  - cd ..\..
test_script:
  - set PATH=C:\mettle;%PATH%
  - set LIBRARY_PATH=C:\mettle
  - set CPPFLAGS=/WX /IC:\mettle
  - 9k build --backend=ninja %EXTRAOPTS%
  - cd build
  - ninja test
