build: false
version: "{branch}-{build}"

image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  PYTHON_PATH: C:\Python37

for:
  - matrix:
      only:
        - image: Visual Studio 2017
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      VCBIN_VER: 14.1
      BOOST_VER: 1_67_0
  - matrix:
      only:
        - image: Visual Studio 2019
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
      VCBIN_VER: 14.2
      BOOST_VER: 1_71_0

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cinst ninja
  - call "%VS%" x86
  - cl.exe
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install bfg9000
  - set BOOST_INCLUDEDIR=C:\Libraries\boost_%BOOST_VER%
  - set BOOST_LIBRARYDIR=C:\Libraries\boost_%BOOST_VER%\lib32-msvc-%VCBIN_VER%

  # Install the latest master revision of mettle.
  - git clone https://github.com/jimporter/mettle.git
  - set CPATH=%CD%\include
  - cd mettle
  - 9k build --backend=ninja --prefix=C:\mettle
  - cd build
  - ninja install
  - cd ..\..
test_script:
  - set PATH=C:\mettle;%PATH%
  - set LIBRARY_PATH=C:\mettle
  - set CPATH=C:\mettle
  - set CPPFLAGS=/WX
  - 9k build --backend=ninja
  - cd build
  - ninja test
